### ISSUE TITLE
Paths with spaces on Windows cannot mount

### ISSUE THREAD

**Issue by noahbkim** [csci104/docker#2]

**Comment by noahbkim** [comment]
You shouldn't even be able to do this from the setup, so some other fix is gonna have to be made.

**Comment by camerondurham** [comment]
Seems to be fixed with new setup script and using `ch` golang CLI.

![image](https://user-images.githubusercontent.com/17013462/105224454-0f599480-5b12-11eb-964a-597d368682fd.png)
