### ISSUE TITLE
clang-format and clang-tidy commands not in container

### ISSUE THREAD

**Issue by aviv-shai** [csci104/docker#5]
I started the Docker container on my machine with the `manage.sh` script; most commands work normally, but `clang-format` and `clang-tidy` both result in `command not found`.

I cloned both this repository (`docker`) and my homework repository (`hw-avivshai`) into `~/Documents/cs104` on my computer. I ran the setup script, `unix/setup.sh`, then ran `./manage.sh start` and `./manage.sh shell` to start the container and open a shell. The shell opened as normal and almost everything worked, but as stated above, the `clang-format` and `clang-tidy` commands did not work.

Here is a screenshot of the output:
![image](https://user-images.githubusercontent.com/68405232/90310213-6f357a80-dea4-11ea-838c-e80ef62f2566.png)

I'm running macOS 10.14.6 (Mojave) on a 2015 Macbook Pro.

**Comment by camerondurham** [comment]
Commit d24e8cb21601ca00de54bc5f53260c5371aca13a closes #5

@aviv-shai Thanks for catching this and filing an issue! Really easy to fix that way.

If you haven't already figured out a solution, here's how you can get clang-tidy, clang-format working: 

1. (fastest) Install dependencies
   - boot into the Docker image: `./manage.sh shell`
   - install missing programs: `apt-get install -y clang-tidy clang-format`
2. Update from latest commit
   - grab the latest commit: `git pull` 
   - rerun `./unix/setup.sh`
